class_name ProductionProcessSystem
extends SimulationSystem


var catalog: ProductionProcessCatalog


func _init() -> void:
	super("production_process_system")
	catalog = ProductionProcessCatalog.new()


func process_month(world: WorldState) -> void:
	if world == null:
		push_error(
			"ProductionProcessSystem: World is null."
		)
		return

	for entity in world.entities.values():

		var industry = entity.get_component(
			"industry"
		)

		var resources = entity.get_component(
			"resources"
		)

		if industry == null:
			continue

		if resources == null:
			continue

		_process_entity(
			entity,
			industry,
			resources,
			world
		)


func _process_entity(
	entity,
	industry: IndustryComponent,
	resources: ResourceComponent,
	world: WorldState
) -> void:

	var processes = industry.get_state(
		"processes",
		{}
	)

	if typeof(processes) != TYPE_DICTIONARY:
		return

	var process_adoption = industry.get_state(
		"process_adoption",
		{}
	)

	if typeof(process_adoption) != TYPE_DICTIONARY:
		process_adoption = {}

	var process_entries: Array = []

	# Step 2.1 — Integrated physical economy:
	# expose the gross resource demand generated by the executable
	# production structure for this monthly process run.
	# This is intentionally separate from ResourceComponent.consumption.
	# ProductionProcessSystem determines industrial input demand; the
	# ResourceSystem will consume/resolve that demand in a later step.
	var production_process_demand: Dictionary = {}

	for process_id in processes.keys():

		var instance = processes[process_id]

		if typeof(instance) != TYPE_DICTIONARY:
			continue

		if not bool(
			instance.get(
				"active",
				false
			)
		):
			continue

		var capacity := float(
			instance.get(
				"capacity",
				0.0
			)
		)

		var efficiency := float(
			instance.get(
				"efficiency",
				1.0
			)
		)

		if capacity <= 0.0:
			continue

		if efficiency <= 0.0:
			continue

		var process_id_string := str(
			process_id
		)

		# Natural-resource extraction is owned by ResourceSystem.
		# ProductionProcessSystem handles industrial transformation.
		if _is_extraction_process(
			process_id_string
		):
			continue

		if not catalog.has_process(
			process_id_string
		):
			continue

		var definition := catalog.get_process(
			process_id_string
		)

		if definition.is_empty():
			continue

		var adoption := clampf(
			float(
				process_adoption.get(
					process_id_string,
					1.0
				)
			),
			0.0,
			1.0
		)

		if adoption <= 0.0:
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "inactive_adoption",
					"blocked": false,
					"reason": "zero_adoption",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": 0.0,
					"operational_factor": 0.0,
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": []
				}
			)
			continue

		# Step 10D — integrate the Step 10C operational consequence
		# into the authoritative production-capacity path. This single
		# resolver applies process adoption, infrastructure-usage
		# bottlenecks, and numeric infrastructure/capability gates.
		# Existing industrial, labor, capital, energy, maintenance,
		# reliability, input, and production logic remains downstream.
		var operational_consequence := (
			IndustryComponent.calculate_entity_process_operational_consequence(
				entity,
				definition,
				capacity,
				adoption
			)
		)

		if bool(
			operational_consequence.get(
				"blocked_by_requirements",
				false
			)
		):
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "blocked",
					"blocked": true,
					"reason": "infrastructure_or_capability_requirement",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": 0.0,
					"operational_factor": float(operational_consequence.get("operational_factor", 0.0)),
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": operational_consequence.get("constraint_sources", [])
				}
			)
			continue

		var operational_capacity := maxf(
			float(
				operational_consequence.get(
					"effective_capacity",
					0.0
				)
			),
			0.0
		)

		if operational_capacity <= 0.0:
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "blocked",
					"blocked": true,
					"reason": "operational_capacity_zero",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": 0.0,
					"operational_factor": float(operational_consequence.get("operational_factor", 0.0)),
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": operational_consequence.get("constraint_sources", [])
				}
			)
			continue

		var industrial_factor := (
			_get_industrial_capacity_factor(
				process_id_string,
				entity
			)
		)

		if industrial_factor <= 0.0:
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "blocked",
					"blocked": true,
					"reason": "industrial_capacity_zero",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": operational_capacity,
					"operational_factor": float(operational_consequence.get("operational_factor", 1.0)),
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": ["industrial_capacity_zero"]
				}
			)
			continue

		# Labor requirements now act as a production-capacity bottleneck.
		# Processes without labor requirements remain neutral.
		var labor_factor := (
			_get_labor_capacity_factor(
				process_id_string,
				entity,
				capacity
			)
		)

		if labor_factor <= 0.0:
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "blocked",
					"blocked": true,
					"reason": "labor_capacity_zero",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": operational_capacity,
					"operational_factor": float(operational_consequence.get("operational_factor", 1.0)),
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": ["labor_capacity_zero"]
				}
			)
			continue

		# Capital requirements now act as another production-capacity
		# bottleneck. The current bridge uses EconomyComponent's
		# investment_capacity as the available capital-capacity pool.
		# This is intentionally a physical-capacity proxy, not yet a
		# full financial capital-market model.
		var capital_factor := (
			_get_capital_capacity_factor(
				process_id_string,
				entity,
				capacity
			)
		)

		if capital_factor <= 0.0:
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "blocked",
					"blocked": true,
					"reason": "capital_capacity_zero",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": operational_capacity,
					"operational_factor": float(operational_consequence.get("operational_factor", 1.0)),
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": ["capital_capacity_zero"]
				}
			)
			continue

		# Explicit power requirements use available power infrastructure
		# as the process-level infrastructure-capacity bridge.
		var energy_factor := (
			_get_energy_capacity_factor(
				process_id_string,
				entity,
				capacity,
				instance
			)
		)

		if energy_factor <= 0.0:
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "blocked",
					"blocked": true,
					"reason": "energy_capacity_zero",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": operational_capacity,
					"operational_factor": float(operational_consequence.get("operational_factor", 1.0)),
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": ["energy_capacity_zero"]
				}
			)
			continue

		# Maintenance requirements now act as a production-capacity
		# bottleneck. Processes without maintenance requirements remain
		# neutral so existing process behavior is unchanged.
		var maintenance_factor := (
			_get_maintenance_capacity_factor(
				process_id_string,
				entity,
				capacity
			)
		)

		if maintenance_factor <= 0.0:
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "blocked",
					"blocked": true,
					"reason": "maintenance_capacity_zero",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": operational_capacity,
					"operational_factor": float(operational_consequence.get("operational_factor", 1.0)),
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": ["maintenance_capacity_zero"]
				}
			)
			continue

		# Reliability is represented deterministically as the portion of
		# the process reliability gap exposed by inadequate maintenance.
		# At full maintenance the process reaches full operational
		# reliability; at lower maintenance its catalog reliability
		# progressively limits available capacity.
		var reliability_factor := (
			_get_reliability_factor(
				process_id_string,
				entity,
				maintenance_factor
			)
		)

		if reliability_factor <= 0.0:
			_record_process_outcome(
				industry,
				process_id_string,
				{
					"status": "blocked",
					"blocked": true,
					"reason": "reliability_capacity_zero",
					"adoption": adoption,
					"base_capacity": capacity,
					"effective_capacity": operational_capacity,
					"operational_factor": float(operational_consequence.get("operational_factor", 1.0)),
					"actual_production": 0.0,
					"inputs_consumed": {},
					"outputs_produced": {},
					"byproducts_produced": {},
					"constraint_sources": ["reliability_capacity_zero"]
				}
			)
			continue

		var usable_capacity := (
			operational_capacity
			* industrial_factor
			* labor_factor
			* capital_factor
			* energy_factor
			* maintenance_factor
			* reliability_factor
		)

		var operational_constraint_factor := clampf(
			float(
				operational_consequence.get(
					"operational_factor",
					1.0
				)
			),
			0.0,
			1.0
		)

		var operational_constraint_sources: Array = operational_consequence.get(
			"constraint_sources",
			[]
		)
		if typeof(operational_constraint_sources) != TYPE_ARRAY:
			operational_constraint_sources = []

		if usable_capacity <= 0.0:
			continue

		var stage := _get_process_stage(
			process_id_string
		)

		process_entries.append({
			"process_id": process_id_string,
			"capacity": usable_capacity,
			"efficiency": efficiency,
			"stage": stage,
			"power_constraint_factor": energy_factor,
			"operational_constraint_factor": operational_constraint_factor,
			"operational_constraint_sources": operational_constraint_sources.duplicate()
		})

	_sort_process_entries(
		process_entries
	)

	for entry in process_entries:

		var entry_process_id := str(
			entry["process_id"]
		)

		var entry_capacity := float(
			entry["capacity"]
		)

		var entry_efficiency := float(
			entry["efficiency"]
		)

		var entry_definition: Dictionary = catalog.get_process(
			entry_process_id
		)

		# Step 2.2 — Resource shortages constrain production.
		#
		# ResourceSystem resolves the previous month's physical resource
		# balance before ProductionProcessSystem runs. The resulting
		# production-process availability factor is applied to process
		# capacity here. The gross Step 2.1 demand is still calculated from
		# the unconstrained entry capacity so the resource shortage remains
		# visible as demand while output is constrained.
		var resource_constraint_factor := (
			_get_production_resource_constraint_factor(
				entry_definition,
				resources
			)
		)

		var allocation_constraint_factor := (
			_get_critical_production_allocation_factor(
				entry_definition,
				resources
			)
		)

		resource_constraint_factor = min(
			resource_constraint_factor,
			allocation_constraint_factor
		)

		var constrained_entry_capacity := (
			entry_capacity
			* resource_constraint_factor
		)

		var execution_result := _execute_process(
			entity,
			entry_process_id,
			constrained_entry_capacity,
			entry_efficiency,
			resources,
			world
		)

		execution_result["resource_constraint_factor"] = (
			resource_constraint_factor
		)

		execution_result["power_constraint_factor"] = clampf(
			float(
				entry.get(
					"power_constraint_factor",
					1.0
				)
			),
			0.0,
			1.0
		)

		execution_result["operational_constraint_factor"] = clampf(
			float(
				entry.get(
					"operational_constraint_factor",
					1.0
				)
			),
			0.0,
			1.0
		)

		var operational_constraint_sources = entry.get(
			"operational_constraint_sources",
			[]
		)
		if typeof(operational_constraint_sources) == TYPE_ARRAY:
			var existing_constraint_sources: Array = execution_result.get(
				"constraint_sources",
				[]
			)
			if typeof(existing_constraint_sources) != TYPE_ARRAY:
				existing_constraint_sources = []
			for source in operational_constraint_sources:
				var source_string := str(source)
				if not existing_constraint_sources.has(source_string):
					existing_constraint_sources.append(source_string)
			execution_result["constraint_sources"] = existing_constraint_sources

		execution_result["allocation_constraint_factor"] = (
			allocation_constraint_factor
		)

		if allocation_constraint_factor < 1.0:
			var allocation_constraint_sources: Array = execution_result.get(
				"constraint_sources",
				[]
			)

			if typeof(allocation_constraint_sources) != TYPE_ARRAY:
				allocation_constraint_sources = []

			if not allocation_constraint_sources.has(
				"allocation_shortfall"
			):
				allocation_constraint_sources.append(
					"allocation_shortfall"
				)

			execution_result["constraint_sources"] = (
				allocation_constraint_sources
			)

		if resource_constraint_factor < 1.0:
			var constraint_sources: Array = execution_result.get(
				"constraint_sources",
				[]
			)

			if typeof(constraint_sources) != TYPE_ARRAY:
				constraint_sources = []

			if not constraint_sources.has(
				"resource_shortage"
			):
				constraint_sources.append(
					"resource_shortage"
				)

			execution_result["constraint_sources"] = constraint_sources

		# Step 2.1 — Production -> resource demand.
		#
		# Only processes that reached execution contribute demand. A normal
		# input shortage still exposes gross demand because that shortage is
		# exactly what the next physical-economy integration step must see.
		# Technology/capability/equipment/infrastructure/process-availability
		# blocks do not create physical input demand.
		var should_record_resource_demand := not bool(
			execution_result.get(
				"blocked",
				false
			)
		)

		if should_record_resource_demand:

			# entry_capacity contains the live production structure before the
			# resource-availability constraint. Keep demand gross here so the
			# resource system can measure unmet physical input requirements.

			# entry_capacity already contains process adoption and all upstream
			# operational/physical capacity factors. Therefore the helper is
			# called with adoption=1.0 here so adoption is not applied twice.
			var entry_resource_demand: Dictionary = (
				calculate_process_resource_demand(
					entry_definition,
					entry_capacity,
					1.0,
					entry_efficiency
				)
			)

			for demand_resource in entry_resource_demand.keys():
				var demand_resource_id := str(
					demand_resource
				)

				production_process_demand[demand_resource_id] = (
					float(
						production_process_demand.get(
							demand_resource_id,
							0.0
						)
					)
					+ float(
						entry_resource_demand[demand_resource]
					)
				)

		# Entries that reach this stage have already passed the
		# operational consequence and all physical-capacity bottlenecks.
		# Persist the authoritative execution result.
		execution_result["adoption"] = clampf(
			float(
				process_adoption.get(
					entry_process_id,
					1.0
				)
			),
			0.0,
			1.0
		)

		_record_process_outcome(
			industry,
			entry_process_id,
			execution_result
		)

	# Replace the previous month's demand state every run so inactive,
	# unavailable, or blocked processes cannot leave stale demand behind.
	resources.set_state(
		"production_process_demand",
		production_process_demand
	)


func _get_production_resource_constraint_factor(
	definition: Dictionary,
	resources: ResourceComponent
) -> float:

	if definition.is_empty():
		return 1.0

	if resources == null:
		return 1.0

	var inputs = definition.get(
		"inputs",
		{}
	)

	if typeof(inputs) != TYPE_DICTIONARY:
		return 1.0

	if inputs.is_empty():
		return 1.0

	var availability = resources.get_state(
		"production_process_resource_availability",
		{}
	)

	if typeof(availability) != TYPE_DICTIONARY:
		return 1.0

	var constraint_factor := 1.0

	for resource_name in inputs.keys():

		var required_per_unit := float(
			inputs[resource_name]
		)

		if required_per_unit <= 0.0:
			continue

		var resource_availability := clampf(
			float(
				availability.get(
					resource_name,
					1.0
				)
			),
			0.0,
			1.0
		)

		constraint_factor = min(
			constraint_factor,
			resource_availability
		)

	return clampf(
		constraint_factor,
		0.0,
		1.0
	)


func _get_critical_production_allocation_factor(
	definition: Dictionary,
	resources: ResourceComponent
) -> float:

	if definition.is_empty():
		return 1.0

	if resources == null:
		return 1.0

	var inputs = definition.get(
		"inputs",
		{}
	)

	if typeof(inputs) != TYPE_DICTIONARY:
		return 1.0

	if inputs.is_empty():
		return 1.0

	var allocation_value = resources.get_state(
		"critical_production_allocation_ratio",
		{}
	)

	if typeof(allocation_value) != TYPE_DICTIONARY:
		return 1.0

	var allocation_factor := 1.0

	for resource_name in inputs.keys():

		var required_per_unit := float(
			inputs[resource_name]
		)

		if required_per_unit <= 0.0:
			continue

		var resource_name_string := str(
			resource_name
		)

		var resource_allocation := clampf(
			float(
				allocation_value.get(
					resource_name_string,
					1.0
				)
			),
			0.0,
			1.0
		)

		allocation_factor = min(
			allocation_factor,
			resource_allocation
		)

	return clampf(
		allocation_factor,
		0.0,
		1.0
	)


# LEGACY HELPER — retained for compatibility only.
# The authoritative production path uses IndustryComponent's live
# operational-consequence resolver instead of this ResourceComponent-only
# calculation.
func _get_infrastructure_capacity_factor(
	process_id: String,
	resources: ResourceComponent
) -> float:

	if resources == null:
		return 1.0

	if not catalog.has_process(
		process_id
	):
		return 1.0

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return 1.0

	var infrastructure_usage = definition.get(
		"infrastructure_usage",
		{}
	)

	if typeof(infrastructure_usage) != TYPE_DICTIONARY:
		return 1.0

	if infrastructure_usage.is_empty():
		return 1.0

	var infrastructure_capacity = resources.get_state(
		"infrastructure_capacity",
		{}
	)

	if typeof(infrastructure_capacity) != TYPE_DICTIONARY:
		return 0.0

	var capacity_factor := 1.0

	for infrastructure_name in infrastructure_usage.keys():

		var required_per_capacity := float(
			infrastructure_usage[infrastructure_name]
		)

		if required_per_capacity <= 0.0:
			continue

		var available_capacity := float(
			infrastructure_capacity.get(
				infrastructure_name,
				0.0
			)
		)

		var infrastructure_factor := (
			available_capacity
			/ required_per_capacity
		)

		capacity_factor = min(
			capacity_factor,
			infrastructure_factor
		)

	return clampf(
		capacity_factor,
		0.0,
		1.0
	)


func _get_industrial_capacity_factor(
	process_id: String,
	entity
) -> float:

	if entity == null:
		return 1.0

	if not catalog.has_process(
		process_id
	):
		return 1.0

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return 1.0

	var industrial_usage = definition.get(
		"industrial_infrastructure_usage",
		{}
	)

	if typeof(industrial_usage) != TYPE_DICTIONARY:
		return 1.0

	if industrial_usage.is_empty():
		return 1.0

	var infrastructure = entity.get_component(
		"infrastructure"
	)

	if infrastructure == null:
		return 0.0

	var industrial_capacity := clampf(
		float(
			infrastructure.get_state(
				"industrial",
				0.0
			)
		),
		0.0,
		1.0
	)

	var capacity_factor := 1.0

	for infrastructure_name in industrial_usage.keys():

		var required_per_capacity := float(
			industrial_usage[infrastructure_name]
		)

		if required_per_capacity <= 0.0:
			continue

		var available_capacity := industrial_capacity

		var infrastructure_factor := (
			available_capacity
			/ required_per_capacity
		)

		capacity_factor = min(
			capacity_factor,
			infrastructure_factor
		)

	return clampf(
		capacity_factor,
		0.0,
		1.0
	)


func _get_labor_capacity_factor(
	process_id: String,
	entity,
	process_capacity: float
) -> float:

	if entity == null:
		return 1.0

	if process_capacity <= 0.0:
		return 0.0

	if not catalog.has_process(
		process_id
	):
		return 1.0

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return 1.0

	var raw_labor_requirement = definition.get(
		"labor_requirement",
		0.0
	)

	var raw_skilled_labor_requirement = definition.get(
		"labor_skill_requirement",
		0.0
	)

	var labor_requirement := 0.0
	var skilled_labor_requirement := 0.0

	if (
		typeof(raw_labor_requirement) == TYPE_INT
		or typeof(raw_labor_requirement) == TYPE_FLOAT
	):
		labor_requirement = maxf(
			float(raw_labor_requirement),
			0.0
		)

	if (
		typeof(raw_skilled_labor_requirement) == TYPE_INT
		or typeof(raw_skilled_labor_requirement) == TYPE_FLOAT
	):
		skilled_labor_requirement = maxf(
			float(raw_skilled_labor_requirement),
			0.0
		)

	if (
		labor_requirement <= 0.0
		and skilled_labor_requirement <= 0.0
	):
		return 1.0

	var population = entity.get_component(
		"population"
	)

	if population == null:
		return 0.0

	var raw_effective_labor = population.get_state(
		"effective_labor_capacity",
		0.0
	)

	var raw_effective_skilled_labor = population.get_state(
		"effective_skilled_labor_capacity",
		0.0
	)

	var effective_labor_capacity := 0.0
	var effective_skilled_labor_capacity := 0.0

	if (
		typeof(raw_effective_labor) == TYPE_INT
		or typeof(raw_effective_labor) == TYPE_FLOAT
	):
		effective_labor_capacity = maxf(
			float(raw_effective_labor),
			0.0
		)

	if (
		typeof(raw_effective_skilled_labor) == TYPE_INT
		or typeof(raw_effective_skilled_labor) == TYPE_FLOAT
	):
		effective_skilled_labor_capacity = maxf(
			float(raw_effective_skilled_labor),
			0.0
		)

	var capacity_factor := 1.0

	if labor_requirement > 0.0:

		var required_labor := (
			process_capacity
			* labor_requirement
		)

		if required_labor > 0.0:
			capacity_factor = min(
				capacity_factor,
				effective_labor_capacity
				/ required_labor
			)

	if skilled_labor_requirement > 0.0:

		var required_skilled_labor := (
			process_capacity
			* skilled_labor_requirement
		)

		if required_skilled_labor > 0.0:
			capacity_factor = min(
				capacity_factor,
				effective_skilled_labor_capacity
				/ required_skilled_labor
			)

	return clampf(
		capacity_factor,
		0.0,
		1.0
	)


func _get_capital_capacity_factor(
	process_id: String,
	entity,
	process_capacity: float
) -> float:

	if entity == null:
		return 1.0

	if process_capacity <= 0.0:
		return 0.0

	if not catalog.has_process(
		process_id
	):
		return 1.0

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return 1.0

	# capital_requirement means capital-capacity units required
	# per unit of installed process capacity.
	#
	# Available capital currently uses the existing
	# EconomyComponent investment_capacity pool. This is a physical
	# capital-capacity bridge, not yet a full financial capital model.
	var raw_capital_requirement = definition.get(
		"capital_requirement",
		0.0
	)

	var capital_requirement := 0.0

	if (
		typeof(raw_capital_requirement) == TYPE_INT
		or typeof(raw_capital_requirement) == TYPE_FLOAT
	):
		capital_requirement = maxf(
			float(raw_capital_requirement),
			0.0
		)

	# No capital requirement = no capital bottleneck.
	if capital_requirement <= 0.0:
		return 1.0

	var economy = entity.get_component(
		"economy"
	)

	if economy == null:
		return 0.0

	var raw_investment_capacity = economy.get_state(
		"investment_capacity",
		0.0
	)

	var available_capital_capacity := 0.0

	if (
		typeof(raw_investment_capacity) == TYPE_INT
		or typeof(raw_investment_capacity) == TYPE_FLOAT
	):
		available_capital_capacity = maxf(
			float(raw_investment_capacity),
			0.0
		)

	var required_capital_capacity := (
		process_capacity
		* capital_requirement
	)

	if required_capital_capacity <= 0.0:
		return 1.0

	var capacity_factor := (
		available_capital_capacity
		/ required_capital_capacity
	)

	return clampf(
		capacity_factor,
		0.0,
		1.0
	)


func _get_process_power_requirement(
	definition: Dictionary,
	process_instance: Dictionary = {}
) -> float:
	# `energy_requirement` is the physical energy/resource demand map.
	# `power_requirement` is the infrastructure-capacity requirement used
	# to translate available power infrastructure into process capacity.
	# A live process-instance override may be used for scenario interventions
	# without mutating the catalog definition. Legacy numeric energy fixtures
	# remain supported as a compatibility path.
	if typeof(process_instance) == TYPE_DICTIONARY:
		var raw_instance_power = process_instance.get(
			"power_requirement",
			null
		)
		if (
			typeof(raw_instance_power) == TYPE_INT
			or typeof(raw_instance_power) == TYPE_FLOAT
		):
			return maxf(float(raw_instance_power), 0.0)

	var raw_power_requirement = definition.get(
		"power_requirement",
		0.0
	)

	if (
		typeof(raw_power_requirement) == TYPE_INT
		or typeof(raw_power_requirement) == TYPE_FLOAT
	):
		return maxf(
			float(raw_power_requirement),
			0.0
		)

	var raw_energy_requirement = definition.get(
		"energy_requirement",
		null
	)

	if (
		typeof(raw_energy_requirement) == TYPE_INT
		or typeof(raw_energy_requirement) == TYPE_FLOAT
	):
		return maxf(
			float(raw_energy_requirement),
			0.0
		)

	return 0.0


func _get_energy_capacity_factor(
	process_id: String,
	entity,
	process_capacity: float,
	process_instance: Dictionary = {}
) -> float:

	if entity == null:
		return 1.0

	if process_capacity <= 0.0:
		return 0.0

	if not catalog.has_process(
		process_id
	):
		return 1.0

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return 1.0

	var power_requirement := _get_process_power_requirement(
		definition,
		process_instance
	)

	# No infrastructure power requirement = no power bottleneck.
	if power_requirement <= 0.0:
		return 1.0

	var infrastructure = entity.get_component(
		"infrastructure"
	)

	if infrastructure == null:
		return 0.0

	var raw_power = infrastructure.get_state(
		"power",
		0.0
	)

	var available_power := 0.0

	if (
		typeof(raw_power) == TYPE_INT
		or typeof(raw_power) == TYPE_FLOAT
	):
		available_power = clampf(
			float(raw_power),
			0.0,
			1.0
		)

	var required_power_capacity := (
		process_capacity
		* power_requirement
	)

	if required_power_capacity <= 0.0:
		return 1.0

	var capacity_factor := (
		available_power
		/ required_power_capacity
	)

	return clampf(
		capacity_factor,
		0.0,
		1.0
	)


func _get_maintenance_capacity_factor(
	process_id: String,
	entity,
	process_capacity: float
) -> float:

	if entity == null:
		return 1.0

	if process_capacity <= 0.0:
		return 0.0

	if not catalog.has_process(
		process_id
	):
		return 1.0

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return 1.0

	var raw_maintenance_requirement = definition.get(
		"maintenance_requirement",
		{}
	)

	if typeof(raw_maintenance_requirement) != TYPE_DICTIONARY:
		return 1.0

	var maintenance_requirement: Dictionary = (
		raw_maintenance_requirement
	)

	if maintenance_requirement.is_empty():
		return 1.0

	var infrastructure = entity.get_component(
		"infrastructure"
	)

	if infrastructure == null:
		return 0.0

	var available_maintenance = infrastructure.get_state(
		"process_maintenance_capacity",
		{}
	)

	if typeof(available_maintenance) != TYPE_DICTIONARY:
		return 0.0

	var capacity_factor := 1.0

	for maintenance_type in maintenance_requirement.keys():

		var raw_requirement = maintenance_requirement[
			maintenance_type
		]

		if (
			typeof(raw_requirement) != TYPE_INT
			and typeof(raw_requirement) != TYPE_FLOAT
		):
			continue

		var requirement_per_capacity := maxf(
			float(raw_requirement),
			0.0
		)

		if requirement_per_capacity <= 0.0:
			continue

		var available_capacity := maxf(
			float(
				available_maintenance.get(
					str(maintenance_type),
					0.0
				)
			),
			0.0
		)

		var required_capacity := (
			process_capacity
			* requirement_per_capacity
		)

		if required_capacity <= 0.0:
			continue

		var maintenance_factor := (
			available_capacity
			/ required_capacity
		)

		capacity_factor = min(
			capacity_factor,
			maintenance_factor
		)

	return clampf(
		capacity_factor,
		0.0,
		1.0
	)


func _get_reliability_factor(
	process_id: String,
	entity,
	maintenance_factor: float
) -> float:

	if entity == null:
		return 1.0

	if not catalog.has_process(
		process_id
	):
		return 1.0

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return 1.0

	var maintenance_requirement = definition.get(
		"maintenance_requirement",
		{}
	)

	if typeof(maintenance_requirement) != TYPE_DICTIONARY:
		return 1.0

	if maintenance_requirement.is_empty():
		return 1.0

	var reliability := clampf(
		float(
			definition.get(
				"reliability",
				1.0
			)
		),
		0.0,
		1.0
	)

	var maintenance = clampf(
		maintenance_factor,
		0.0,
		1.0
	)

	# The maintenance factor controls how much of the process can be
	# maintained. Reliability determines the residual operational risk.
	# Full maintenance removes that maintenance-exposed reliability gap;
	# insufficient maintenance exposes it progressively.
	return clampf(
		1.0
		- (
			1.0 - reliability
		)
		* (
			1.0 - maintenance
		),
		0.0,
		1.0
	)


func _is_extraction_process(
	process_id: String
) -> bool:

	if not catalog.has_process(
		process_id
	):
		return false

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return false

	var category := str(
		definition.get(
			"category",
			""
		)
	).to_lower()

	return category == "extraction"


func _sort_process_entries(
	entries: Array
) -> void:

	entries.sort_custom(
		func(a, b):
			var stage_a := float(
				a.get(
					"stage",
					0.0
				)
			)

			var stage_b := float(
				b.get(
					"stage",
					0.0
				)
			)

			if stage_a != stage_b:
				return stage_a < stage_b

			var id_a := str(
				a.get(
					"process_id",
					""
				)
			)

			var id_b := str(
				b.get(
					"process_id",
					""
				)
			)

			return id_a < id_b
	)


func _get_process_stage(
	process_id: String
) -> float:

	if not catalog.has_process(
		process_id
	):
		return 0.0

	var definition := catalog.get_process(
		process_id
	)

	if definition.is_empty():
		return 0.0

	return float(
		definition.get(
			"production_stage",
			0
		)
	)


# ----------------------------------------------------------------
# Step 9 — Resource demand caused by process adoption
#
# These helpers calculate gross resource demand from a process mix.
# They do not consume stockpiles and do not alter production.
# Actual stockpile consumption remains in _execute_process().
# ----------------------------------------------------------------

static func calculate_resource_demand(
	inputs: Dictionary,
	production_amount: float
) -> Dictionary:

	var demand := {}
	var amount := maxf(
		production_amount,
		0.0
	)

	if amount <= 0.0:
		return demand

	for resource_name in inputs.keys():

		var required_per_unit := float(
			inputs[resource_name]
		)

		if required_per_unit <= 0.0:
			continue

		demand[str(resource_name)] = (
			required_per_unit
			* amount
		)

	return demand


static func calculate_process_resource_demand(
	definition: Dictionary,
	process_capacity: float,
	adoption: float = 1.0,
	operational_efficiency: float = 1.0
) -> Dictionary:

	if definition.is_empty():
		return {}

	var inputs = definition.get(
		"inputs",
		{}
	)

	if typeof(inputs) != TYPE_DICTIONARY:
		return {}

	var capacity := maxf(
		process_capacity,
		0.0
	)

	var adoption_value := clampf(
		adoption,
		0.0,
		1.0
	)

	var operational_factor := clampf(
		operational_efficiency,
		0.0,
		1.0
	)

	var catalog_efficiency := maxf(
		float(
			definition.get(
				"efficiency",
				1.0
			)
		),
		0.0
	)

	var production_amount := (
		capacity
		* adoption_value
		* catalog_efficiency
		* operational_factor
	)

	return calculate_resource_demand(
		inputs,
		production_amount
	)


static func calculate_resource_demand_for_process_mix(
	process_definitions: Dictionary,
	process_capacities: Dictionary,
	process_adoption: Dictionary,
	operational_efficiencies: Dictionary = {}
) -> Dictionary:

	var total_demand := {}

	for process_id in process_definitions.keys():

		var definition = process_definitions[
			process_id
		]

		if typeof(definition) != TYPE_DICTIONARY:
			continue

		var process_id_string := str(
			process_id
		)

		var capacity := float(
			process_capacities.get(
				process_id_string,
				process_capacities.get(
					process_id,
					0.0
				)
			)
		)

		var adoption := float(
			process_adoption.get(
				process_id_string,
				process_adoption.get(
					process_id,
					0.0
				)
			)
		)

		var operational_efficiency := float(
			operational_efficiencies.get(
				process_id_string,
				operational_efficiencies.get(
					process_id,
					1.0
				)
			)
		)

		var process_demand := (
			calculate_process_resource_demand(
				definition,
				capacity,
				adoption,
				operational_efficiency
			)
		)

		for resource_name in process_demand.keys():

			var resource_id := str(
				resource_name
			)

			total_demand[resource_id] = (
				float(
					total_demand.get(
						resource_id,
						0.0
					)
				)
				+ float(
					process_demand[resource_name]
				)
			)

	return total_demand


func _execute_process(
	entity,
	process_id: String,
	capacity: float,
	efficiency: float,
	resources: ResourceComponent,
	world: WorldState
) -> Dictionary:

	var result := {
		"status": "not_executed",
		"blocked": false,
		"reason": "",
		"actual_production": 0.0,
		"effective_capacity": maxf(capacity, 0.0),
		"operational_factor": 1.0,
		"resource_constraint_factor": 1.0,
		"power_constraint_factor": 1.0,
		"operational_constraint_factor": 1.0,
		"inputs_consumed": {},
		"outputs_produced": {},
		"byproducts_produced": {},
		"constraint_sources": []
	}

	if not catalog.has_process(process_id):
		result["status"] = "skipped"
		result["reason"] = "unknown_process"
		return result

	var definition := catalog.get_process(process_id)

	if definition.is_empty():
		result["status"] = "skipped"
		result["reason"] = "empty_process_definition"
		return result

	if not _is_process_available(definition, world):
		result["status"] = "blocked"
		result["blocked"] = true
		result["reason"] = "process_unavailable"
		return result

	if not _are_process_requirements_met(entity, resources, definition):
		result["status"] = "blocked"
		result["blocked"] = true
		result["reason"] = "requirements_not_met"
		return result

	var catalog_efficiency := float(
		definition.get("efficiency", 1.0)
	)

	var inputs = definition.get("inputs", {})
	var outputs = definition.get("outputs", {})
	var byproducts = definition.get("byproducts", {})

	if typeof(inputs) != TYPE_DICTIONARY:
		inputs = {}
	if typeof(outputs) != TYPE_DICTIONARY:
		outputs = {}
	if typeof(byproducts) != TYPE_DICTIONARY:
		byproducts = {}

	var effective_efficiency := (
		catalog_efficiency
		* clampf(efficiency, 0.0, 1.0)
	)

	var effective_capacity: float = (
		maxf(capacity, 0.0)
		* maxf(effective_efficiency, 0.0)
	)

	result["effective_capacity"] = effective_capacity

	if effective_capacity <= 0.0:
		result["status"] = "no_capacity"
		result["reason"] = "effective_capacity_zero"
		return result

	var stockpile = resources.get_state("stockpile", {})

	if typeof(stockpile) != TYPE_DICTIONARY:
		result["status"] = "blocked"
		result["blocked"] = true
		result["reason"] = "invalid_stockpile_state"
		return result

	var production_fraction := 1.0

	for resource_name in inputs.keys():
		var required_per_unit := float(inputs[resource_name])

		if required_per_unit <= 0.0:
			continue

		var available := float(stockpile.get(resource_name, 0.0))
		var possible_units := available / required_per_unit

		production_fraction = min(
			production_fraction,
			possible_units / effective_capacity
		)

	production_fraction = clampf(
		production_fraction,
		0.0,
		1.0
	)

	var actual_production: float = (
		effective_capacity
		* production_fraction
	)

	result["actual_production"] = actual_production

	if actual_production <= 0.0:
		result["status"] = "no_output"
		result["reason"] = "input_shortage_or_zero_supply"
		return result

	var inputs_consumed := {}
	var outputs_produced := {}
	var byproducts_produced := {}

	for resource_name in inputs.keys():
		var required_per_unit := float(inputs[resource_name])
		var consumed := required_per_unit * actual_production

		stockpile[resource_name] = max(
			0.0,
			float(stockpile.get(resource_name, 0.0)) - consumed
		)

		inputs_consumed[str(resource_name)] = consumed

	for resource_name in outputs.keys():
		var output_per_unit := float(outputs[resource_name])
		var produced := output_per_unit * actual_production

		stockpile[resource_name] = (
			float(stockpile.get(resource_name, 0.0))
			+ produced
		)

		outputs_produced[str(resource_name)] = produced

	for resource_name in byproducts.keys():
		var byproduct_per_unit := float(byproducts[resource_name])
		var produced := byproduct_per_unit * actual_production

		stockpile[resource_name] = (
			float(stockpile.get(resource_name, 0.0))
			+ produced
		)

		byproducts_produced[str(resource_name)] = produced

	resources.set_state("stockpile", stockpile)

	result["status"] = "produced"
	result["inputs_consumed"] = inputs_consumed
	result["outputs_produced"] = outputs_produced
	result["byproducts_produced"] = byproducts_produced

	return result


func _record_process_outcome(
	industry: IndustryComponent,
	process_id: String,
	outcome: Dictionary
) -> void:

	if industry == null:
		return

	industry.record_production_outcome(
		process_id,
		outcome
	)


func _are_process_requirements_met(
	entity,
	resources: ResourceComponent,
	definition: Dictionary
) -> bool:

	if entity == null:
		return false

	if resources == null:
		return false

	# Technology requirements are evaluated against
	# the country's current technology adoption state.
	var technology_requirements = definition.get(
		"technology_requirements",
		{}
	)

	if typeof(technology_requirements) != TYPE_DICTIONARY:
		technology_requirements = {}

	var technology_available: Dictionary = {}

	var technology_adoption = entity.get_component(
		"technology_adoption"
	)

	if technology_adoption != null:

		var adoption_state = technology_adoption.get_state(
			"adoption",
			{}
		)

		if typeof(adoption_state) == TYPE_DICTIONARY:
			technology_available = adoption_state.duplicate(
				true
			)

	if not ProductionProcessRequirementEvaluator.requirements_met(
		technology_requirements,
		technology_available
	):
		return false


	# Capability requirements are evaluated against
	# the capabilities rebuilt by CapabilitySystem.
	var capability_requirements = definition.get(
		"capability_requirements",
		{}
	)

	if typeof(capability_requirements) != TYPE_DICTIONARY:
		capability_requirements = {}

	var capabilities = entity.get_sim_metadata(
		"capabilities",
		{}
	)

	if typeof(capabilities) != TYPE_DICTIONARY:
		capabilities = {}

	if not ProductionProcessRequirementEvaluator.requirements_met(
		capability_requirements,
		capabilities
	):
		return false


	# Equipment requirements are evaluated against
	# industrial equipment capabilities exposed through
	# the existing capability metadata.
	var equipment_requirements = definition.get(
		"equipment_requirement",
		{}
	)

	if typeof(equipment_requirements) != TYPE_DICTIONARY:
		equipment_requirements = {}

	if not ProductionProcessRequirementEvaluator.requirements_met(
		equipment_requirements,
		capabilities
	):
		return false


	# Step 10D uses the same live infrastructure availability source
	# as IndustryComponent's operational-consequence resolver. It resolves
	# named process infrastructure capacity from InfrastructureComponent
	# first and uses ResourceComponent.infrastructure_capacity only as a
	# compatibility fallback.
	var infrastructure_requirements = definition.get(
		"infrastructure_requirements",
		{}
	)

	if typeof(infrastructure_requirements) != TYPE_DICTIONARY:
		infrastructure_requirements = {}

	var infrastructure_capacity := (
		IndustryComponent.get_entity_infrastructure_availability(
			entity
		)
	)

	if not ProductionProcessRequirementEvaluator.requirements_met(
		infrastructure_requirements,
		infrastructure_capacity
	):
		return false

	return true


func _is_process_available(
	definition: Dictionary,
	world: WorldState
) -> bool:

	if world == null:
		return false

	var simulation_date = world.get(
		"date"
	)

	if simulation_date == null:
		return true

	var year := 0

	if typeof(simulation_date) == TYPE_OBJECT:

		if "year" in simulation_date:
			year = int(
				simulation_date.year
			)

	elif typeof(simulation_date) == TYPE_DICTIONARY:

		year = int(
			simulation_date.get(
				"year",
				0
			)
		)

	if year <= 0:
		return true

	var available_from := int(
		definition.get(
			"available_from",
			-999999
		)
	)

	if year < available_from:
		return false

	var available_until_value = (
		definition.get(
			"available_until",
			null
		)
	)

	if available_until_value != null:

		var available_until := int(
			available_until_value
		)

		if year > available_until:
			return false

	return true
