class_name ResourceSystem
extends SimulationSystem


var catalog: ResourceCatalog


func _init():
	super("resource_system")
	catalog = ResourceCatalog.new()


func process_month(world: WorldState) -> void:

	if world == null:
		push_error("ResourceSystem: World is null.")
		return

	for entity in world.entities.values():

		var resources = entity.get_component("resources")

		if resources == null:
			continue

		_process_entity_resources(entity, resources)



func _get_effective_infrastructure_value(
	infrastructure,
	infrastructure_type: String,
	fallback: float = 1.0
) -> float:

	if infrastructure == null:
		return fallback

	# Step 14.2 derived capacity is authoritative only when there is an
	# active post-processing condition (damage and/or maintenance). The
	# legacy ResourceSystem test suite directly mutates raw infrastructure
	# values without always running InfrastructureSystem afterward. In that
	# neutral state the raw component value remains the current input.
	var damage_state = infrastructure.get_state(
		"infrastructure_damage",
		{}
	)

	var has_active_damage := false

	if damage_state is Dictionary:
		for value in damage_state.values():
			if float(value) > 0.0:
				has_active_damage = true
				break

	var condition_state = infrastructure.get_state(
		"infrastructure_condition",
		{}
	)

	var has_non_neutral_condition := false

	if condition_state is Dictionary:
		for value in condition_state.values():
			if abs(float(value) - 1.0) > 0.000001:
				has_non_neutral_condition = true
				break

	if has_active_damage or has_non_neutral_condition:
		var effective_capacity = infrastructure.get_state(
			"effective_infrastructure_capacity",
			{}
		)

		if (
			effective_capacity is Dictionary
			and effective_capacity.has(infrastructure_type)
		):
			return clamp(
				float(
					effective_capacity.get(
						infrastructure_type,
						fallback
					)
				),
				0.0,
				1.0
			)

	# Neutral/no-derived-state path:
	# preserve the existing ResourceSystem behavior and read the current raw
	# infrastructure value directly.
	return float(
		infrastructure.get_state(
			infrastructure_type,
			fallback
		)
	)

func _process_entity_resources(
	entity,
	resources: ResourceComponent
) -> void:

	var production = resources.get_state("production", {})
	var consumption = resources.get_state("consumption", {})
	var reserves = resources.get_state("reserves", {})
	var stockpile = resources.get_state("stockpile", {})
	var imports = resources.get_state("imports", {})
	var exports = resources.get_state("exports", {})

	# TradeSystem 4.5 writes flows that have already been constrained
	# by the physical infrastructure chain. ResourceSystem uses these
	# states to avoid applying port throughput a second time.
	var trade_imports = resources.get_state("trade_imports", {})
	var trade_exports = resources.get_state("trade_exports", {})

	# Step 2.2 — gross production-process input demand generated by the
	# previous ProductionProcessSystem run. This state is intentionally
	# separate from general ResourceComponent.consumption so the existing
	# resource-demand lifecycle remains unchanged.
	var production_process_demand = resources.get_state(
		"production_process_demand",
		{}
	)

	var extraction_capacity = resources.get_state(
		"extraction_capacity",
		{}
	)

	var processing_capacity = resources.get_state(
		"processing_capacity",
		{}
	)

	var production_efficiency = resources.get_state(
		"production_efficiency",
		{}
	)

	var technology_efficiency = resources.get_state(
		"technology_efficiency",
		{}
	)

	var technology_access = resources.get_state(
		"technology_access",
		{}
	)

	var infrastructure_capacity = resources.get_state(
		"infrastructure_capacity",
		{}
	)

	var quality = resources.get_state(
		"quality",
		{}
	)

	var accessibility = resources.get_state(
		"accessibility",
		{}
	)

	# Optional absolute stockpile limits. A resource is capped only when
	# its entry exists in this dictionary; otherwise the existing unlimited
	# stockpile behavior is preserved for backward compatibility.
	var max_stockpile_capacity = resources.get_state(
		"max_stockpile_capacity",
		{}
	)

	var resource_names: Dictionary = {}

	_collect_resource_names(
		resource_names,
		production
	)

	_collect_resource_names(
		resource_names,
		consumption
	)

	_collect_resource_names(
		resource_names,
		reserves
	)

	_collect_resource_names(
		resource_names,
		stockpile
	)

	_collect_resource_names(
		resource_names,
		imports
	)

	_collect_resource_names(
		resource_names,
		exports
	)

	_collect_resource_names(
		resource_names,
		extraction_capacity
	)

	_collect_resource_names(
		resource_names,
		processing_capacity
	)

	_collect_resource_names(
		resource_names,
		production_process_demand
	)

	_collect_resource_names(
		resource_names,
		max_stockpile_capacity
	)

	var configured_commitments = resources.get_state(
		"committed_stockpile",
		{}
	)

	_collect_resource_names(
		resource_names,
		configured_commitments
	)

	var net_balance: Dictionary = {}

	# Step 5.1 — explicit stock/flow accounting.
	# These states record the monthly opening stock, settled flows,
	# closing stock and reconciliation status without changing the
	# existing stockpile/shortage/overflow calculation.
	var opening_stockpile: Dictionary = {}
	var closing_stockpile: Dictionary = {}
	var fulfilled_demand: Dictionary = {}
	var stock_flow_ledger: Dictionary = {}
	var stock_flow_reconciliation_error: Dictionary = {}
	var opening_reserves: Dictionary = {}
	var closing_reserves: Dictionary = {}
	var reserve_flow_reconciliation_error: Dictionary = {}

	# Step 5.2 — explicit inventory-buffer semantics.
	# These are reservation/availability overlays on the physical stockpile;
	# they do not create a second inventory store.
	var committed_stockpile: Dictionary = {}
	var secured_commitment: Dictionary = {}
	var commitment_shortfall: Dictionary = {}
	var available_stockpile: Dictionary = {}
	var available_supply_by_resource: Dictionary = {}
	var closing_committed_stockpile: Dictionary = {}
	var closing_available_stockpile: Dictionary = {}
	var closing_commitment_shortfall: Dictionary = {}
	var inventory_buffer_ledger: Dictionary = {}

	var shortages: Dictionary = {}
	var shortage_ratio: Dictionary = {}
	var reserve_depletion: Dictionary = {}
	var actual_production: Dictionary = {}
	var surplus: Dictionary = {}
	var reserve_ratio: Dictionary = {}
	var storage_overflow: Dictionary = {}

	# Step 2.2 feedback states. These describe how much of the next
	# month's gross production-process input demand can be physically
	# supplied by the resource state produced this month.
	var production_process_shortages: Dictionary = {}
	var production_process_shortage_ratio: Dictionary = {}
	var production_process_resource_availability: Dictionary = {}

	# ====================================================
	# PER-RESOURCE EFFECTS
	# ====================================================

	var resource_efficiency_by_resource: Dictionary = {}
	var industrial_modifier_by_resource: Dictionary = {}
	var military_modifier_by_resource: Dictionary = {}
	var transport_modifier_by_resource: Dictionary = {}

	# Aggregate country-level effects.
	#
	# These represent the most limiting resource rather than
	# multiplying every resource's effect together.
	var total_resource_efficiency := 1.0
	var total_industrial_modifier := 1.0
	var total_military_modifier := 1.0
	var total_transport_modifier := 1.0

	for resource_name in resource_names.keys():

		var requested_production = float(
			production.get(
				resource_name,
				0.0
			)
		)

		var consumed = float(
			consumption.get(
				resource_name,
				0.0
			)
		)

		var imported = float(
			imports.get(
				resource_name,
				0.0
			)
		)

		var exported = float(
			exports.get(
				resource_name,
				0.0
			)
		)

		var current_stockpile = float(
			stockpile.get(
				resource_name,
				0.0
			)
		)

		var current_reserves = float(
			reserves.get(
				resource_name,
				0.0
			)
		)

		# ====================================================
		# STEP 5.2 — OPENING INVENTORY BUFFER SEMANTICS
		# ====================================================
		#
		# reserves are not inventory available for civilian/industrial
		# demand. They remain the physical extraction base already used
		# by ResourceSystem. stockpile is the physical stored inventory.
		# committed_stockpile is a reservation over that stockpile, so the
		# same units cannot simultaneously be treated as freely available.
		#
		# The requested commitment is intentionally not written back or
		# destroyed here. A future allocation/action system owns commitment
		# lifecycle. ResourceSystem only derives secured/unsecured amounts.
		# ====================================================

		var requested_commitment = max(
			0.0,
			float(
				configured_commitments.get(
					resource_name,
					0.0
				)
			)
		)

		var opening_secured_commitment = min(
			requested_commitment,
			current_stockpile
		)

		var opening_commitment_shortfall = max(
			requested_commitment
			- opening_secured_commitment,
			0.0
		)

		var opening_available_stockpile = max(
			current_stockpile
			- opening_secured_commitment,
			0.0
		)
		# ====================================================

		if not extraction_capacity.has(resource_name):

			extraction_capacity[resource_name] = max(
				0.0,
				requested_production
			)

		if not processing_capacity.has(resource_name):

			processing_capacity[resource_name] = max(
				0.0,
				requested_production
			)

		var extraction_limit = float(
			extraction_capacity.get(
				resource_name,
				requested_production
			)
		)

		var processing_limit = float(
			processing_capacity.get(
				resource_name,
				extraction_limit
			)
		)

		var base_efficiency = float(
			production_efficiency.get(
				resource_name,
				1.0
			)
		)

		var tech_efficiency = float(
			technology_efficiency.get(
				resource_name,
				1.0
			)
		)

		var infrastructure_modifier = float(
			infrastructure_capacity.get(
				resource_name,
				1.0
			)
		)

		# Specialized transport infrastructure acts as a
		# direct production constraint.
		var specialized_transport_capacity := 1.0

		# Power infrastructure acts as a direct production
		# capacity constraint at the resource-extraction level.
		# This is an infrastructure abstraction; detailed process
		# energy requirements remain owned by ProductionProcessSystem.
		var specialized_power_capacity := 1.0

		# Ports constrain international resource throughput.
		# They do not directly reduce domestic production; they limit
		# how much of the requested import/export flow can actually
		# cross the country's port capacity this month.
		var port_throughput_capacity := 1.0

		# Roads and railways act as coarse upper bounds on
		# resource accessibility. They do not add independent
		# production multipliers; instead they constrain the
		# accessibility factor already present in ResourceComponent.
		var road_accessibility_limit := 1.0
		var railway_accessibility_limit := 1.0

		var infrastructure = entity.get_component(
			"infrastructure"
		)

		if infrastructure != null:
			specialized_transport_capacity = _get_effective_infrastructure_value(
				infrastructure,
				"transport",
				1.0
			)

			port_throughput_capacity = _get_effective_infrastructure_value(
				infrastructure,
				"ports",
				1.0
			)

			road_accessibility_limit = _get_effective_infrastructure_value(
				infrastructure,
				"roads",
				1.0
			)

			specialized_power_capacity = _get_effective_infrastructure_value(
				infrastructure,
				"power",
				1.0
			)

			railway_accessibility_limit = _get_effective_infrastructure_value(
				infrastructure,
				"railways",
				1.0
			)

		specialized_transport_capacity = clamp(
			specialized_transport_capacity,
			0.0,
			1.0
		)

		port_throughput_capacity = clamp(
			port_throughput_capacity,
			0.0,
			1.0
		)

		road_accessibility_limit = clamp(
			road_accessibility_limit,
			0.0,
			1.0
		)

		specialized_power_capacity = clamp(
			specialized_power_capacity,
			0.0,
			1.0
		)

		railway_accessibility_limit = clamp(
			railway_accessibility_limit,
			0.0,
			1.0
		)

		var resource_quality = float(
			quality.get(
				resource_name,
				1.0
			)
		)

		var resource_accessibility = float(
			accessibility.get(
				resource_name,
				1.0
			)
		)

		var effective_resource_accessibility = min(
			clamp(
				resource_accessibility,
				0.0,
				1.0
			),
			road_accessibility_limit,
			railway_accessibility_limit
		)

		var effective_efficiency = clamp(
			base_efficiency
			* tech_efficiency
			* infrastructure_modifier
			* specialized_transport_capacity
			* specialized_power_capacity
			* resource_quality
			* effective_resource_accessibility,
			0.0,
			1.5
		)

		# ====================================================
		# ACTUAL PRODUCTION
		# ====================================================

		var production_limit = min(
			extraction_limit,
			processing_limit
		)

		var produced = min(
			requested_production,
			production_limit
		)

		produced *= effective_efficiency

		if reserves.has(resource_name):

			produced = min(
				produced,
				current_reserves
			)

		produced = max(
			0.0,
			produced
		)

		actual_production[resource_name] = produced

		# ====================================================
		# RESERVE DEPLETION
		# ====================================================

		var depleted = 0.0

		if reserves.has(resource_name):

			depleted = produced

			reserves[resource_name] = max(
				0.0,
				current_reserves - depleted
			)

		reserve_depletion[resource_name] = depleted

		# ====================================================
		# RESERVE RATIO
		# ====================================================

		var starting_reserves = current_reserves
		var remaining_reserves = current_reserves

		if reserves.has(resource_name):

			remaining_reserves = float(
				reserves.get(
					resource_name,
					0.0
				)
			)

			if starting_reserves > 0.0:

				reserve_ratio[resource_name] = (
					remaining_reserves
					/ starting_reserves
				)

			else:

				reserve_ratio[resource_name] = 0.0

		else:

			reserve_ratio[resource_name] = 1.0

		# ====================================================
		# INTERNATIONAL THROUGHPUT
		# ====================================================

		# Imports and exports normally represent requested / scheduled flows,
		# so ResourceSystem applies the country's existing port throughput.
		# TradeSystem 4.5 additionally records the portion already resolved by
		# the complete physical trade chain. That portion must be settled as-is
		# rather than being multiplied by port capacity again. Any remaining
		# non-trade flow retains the original port-throughput behavior.
		var trade_imported = max(
			0.0,
			float(trade_imports.get(resource_name, 0.0))
		)

		var trade_exported = max(
			0.0,
			float(trade_exports.get(resource_name, 0.0))
		)

		trade_imported = min(
			trade_imported,
			max(0.0, imported)
		)

		trade_exported = min(
			trade_exported,
			max(0.0, exported)
		)

		var non_trade_imported = max(
			0.0,
			max(0.0, imported) - trade_imported
		)

		var non_trade_exported = max(
			0.0,
			max(0.0, exported) - trade_exported
		)

		var effective_imported = (
			trade_imported
			+ non_trade_imported * port_throughput_capacity
		)

		var effective_exported = (
			trade_exported
			+ non_trade_exported * port_throughput_capacity
		)

		# ====================================================
		# AVAILABLE SUPPLY
		# ====================================================

		var resource_available_supply = (
			opening_available_stockpile
			+ produced
			+ effective_imported
		)

		var total_physical_supply = (
			current_stockpile
			+ produced
			+ effective_imported
		)

		# Preserve the Step 5.1 settlement identity. Step 5.2 exposes
		# available_supply as the uncommitted buffer plus current inflows;
		# demand settlement itself remains owned by the existing resource
		# flow logic until Step 5.3 introduces demand categories/allocation.

		# ====================================================
		# TOTAL DEMAND
		# ====================================================

		var total_demand = (
			consumed
			+ effective_exported
		)

		# ====================================================
		# STOCKPILE
		# ====================================================

		var new_stockpile = (
			total_physical_supply
			- total_demand
		)

		# Storage is an absolute stockpile ceiling when a capacity is
		# defined for this resource. Consumption/export demand is settled
		# first. Any amount above the ceiling is explicitly recorded as
		# storage overflow before the stockpile is clamped.
		var overflow_amount := 0.0

		if max_stockpile_capacity.has(resource_name):

			var stockpile_capacity = max(
				0.0,
				float(
					max_stockpile_capacity.get(
						resource_name,
						0.0
					)
				)
			)

			if new_stockpile > stockpile_capacity:
				overflow_amount = (
					new_stockpile
					- stockpile_capacity
				)

			new_stockpile = min(
				new_stockpile,
				stockpile_capacity
			)

		storage_overflow[resource_name] = max(
			0.0,
			overflow_amount
		)

		var shortage = 0.0
		var shortage_percentage = 0.0

		if new_stockpile < 0.0:

			shortage = abs(
				new_stockpile
			)

			new_stockpile = 0.0

			if total_demand > 0.0:

				shortage_percentage = (
					shortage
					/ total_demand
				) * 100.0

		shortage_percentage = clamp(
			shortage_percentage,
			0.0,
			100.0
		)

		stockpile[resource_name] = new_stockpile

		shortages[resource_name] = shortage

		shortage_ratio[resource_name] = (
			shortage_percentage
		)

		# Step 2.2 — production-process resource availability.
		#
		# This uses the settled end-of-resource-system stockpile. Because
		# ResourceSystem runs before ProductionProcessSystem, this is the
		# physical resource availability carried into the production pass
		# for the current simulation month. It prevents a circular
		# same-month dependency while allowing shortage feedback to persist.
		var production_demand := float(
			production_process_demand.get(
				resource_name,
				0.0
			)
		)

		var production_shortage :float= max(
			production_demand
			- new_stockpile,
			0.0
		)

		var production_shortage_percentage := 0.0

		if production_demand > 0.0:
			production_shortage_percentage = (
				production_shortage
				/ production_demand
			) * 100.0

		production_shortage_percentage = clamp(
			production_shortage_percentage,
			0.0,
			100.0
		)

		var production_availability := 1.0

		if production_demand > 0.0:
			production_availability = clamp(
				new_stockpile
				/ production_demand,
				0.0,
				1.0
			)

		production_process_shortages[resource_name] = (
			production_shortage
		)

		production_process_shortage_ratio[resource_name] = (
			production_shortage_percentage
		)

		production_process_resource_availability[resource_name] = (
			production_availability
		)

		# ====================================================
		# SURPLUS
		# ====================================================

		var current_surplus = max(
			0.0,
			new_stockpile
		)

		surplus[resource_name] = current_surplus

		# ====================================================
		# NET BALANCE
		# ====================================================

		var balance = (
			produced
			+ effective_imported
			- consumed
			- effective_exported
		)

		net_balance[resource_name] = balance

		# ====================================================
		# STEP 5.1 — STOCK / FLOW ACCOUNTING
		# ====================================================
		#
		# Preserve the existing resource-settlement behavior, but make the
		# accounting identity explicit. The requested consumption/export
		# values remain unchanged; shortage represents demand that could not
		# be fulfilled, and storage_overflow represents material that could
		# not remain in stock because of the stockpile ceiling.
		#
		# Physical identity:
		#
		# opening stock
		# + actual production
		# + effective imports
		# = fulfilled demand
		# + closing stock
		# + storage overflow
		#
		# where fulfilled demand = requested demand - shortage.
		# ====================================================

		var resource_fulfilled_demand: float = max(
			total_demand
			- shortage,
			0.0
		)

		var stock_flow_error: float = (
			current_stockpile
			+ produced
			+ effective_imported
			- resource_fulfilled_demand
			- new_stockpile
			- overflow_amount
		)

		var reserve_flow_error: float = (
			starting_reserves
			- depleted
			- remaining_reserves
		)

		opening_stockpile[resource_name] = current_stockpile
		closing_stockpile[resource_name] = new_stockpile
		fulfilled_demand[resource_name] = resource_fulfilled_demand
		stock_flow_reconciliation_error[resource_name] = stock_flow_error
		opening_reserves[resource_name] = starting_reserves
		closing_reserves[resource_name] = remaining_reserves
		reserve_flow_reconciliation_error[resource_name] = reserve_flow_error

		stock_flow_ledger[resource_name] = {
			"opening_stockpile": current_stockpile,
			"production": produced,
			"imports": effective_imported,
			"consumption": consumed,
			"exports": effective_exported,
			"total_demand": total_demand,
			"fulfilled_demand": resource_fulfilled_demand,
			"shortage": shortage,
			"storage_overflow": overflow_amount,
			"net_balance": balance,
			"physical_net_change": (
				new_stockpile
				- current_stockpile
			),
			"closing_stockpile": new_stockpile,
			"reconciliation_error": stock_flow_error,
			"opening_reserves": starting_reserves,
			"reserve_depletion": depleted,
			"closing_reserves": remaining_reserves,
			"reserve_reconciliation_error": reserve_flow_error
		}

		# ====================================================
		# STEP 5.2 — INVENTORY / STOCK BUFFER SEMANTICS
		# ====================================================
		# committed_stockpile is an overlay on physical stock, not a second
		# stock store. It stays at the requested amount until the system
		# that owns the obligation explicitly changes it. ResourceSystem
		# therefore reports how much is secured by the physical stockpile.
		var closing_secured_commitment = min(
			requested_commitment,
			new_stockpile
		)

		var closing_commitment_gap = max(
			requested_commitment
			- closing_secured_commitment,
			0.0
		)

		var closing_available_stock = max(
			new_stockpile
			- closing_secured_commitment,
			0.0
		)

		committed_stockpile[resource_name] = requested_commitment
		secured_commitment[resource_name] = opening_secured_commitment
		commitment_shortfall[resource_name] = opening_commitment_shortfall
		available_stockpile[resource_name] = opening_available_stockpile
		available_supply_by_resource[resource_name] = resource_available_supply
		closing_committed_stockpile[resource_name] = requested_commitment
		closing_available_stockpile[resource_name] = closing_available_stock
		closing_commitment_shortfall[resource_name] = closing_commitment_gap

		inventory_buffer_ledger[resource_name] = {
			"opening_stockpile": current_stockpile,
			"opening_committed_quantity": requested_commitment,
			"opening_secured_commitment": opening_secured_commitment,
			"opening_commitment_shortfall": opening_commitment_shortfall,
			"opening_available_stockpile": opening_available_stockpile,
			"production": produced,
			"effective_imports": effective_imported,
			"available_supply_before_current_demand": resource_available_supply,
			"closing_stockpile": new_stockpile,
			"closing_committed_quantity": requested_commitment,
			"closing_secured_commitment": closing_secured_commitment,
			"closing_commitment_shortfall": closing_commitment_gap,
			"closing_available_stockpile": closing_available_stock
		}

		# ====================================================
		# RESOURCE EFFECTS
		# ====================================================

		var shortage_effect = (
			1.0
			- (shortage_percentage / 100.0)
		)

		shortage_effect = clamp(
			shortage_effect,
			0.0,
			1.0
		)

		var resource_modifier = (
			0.5
			+ shortage_effect * 0.5
		)

		var industrial_modifier = (
			0.6
			+ shortage_effect * 0.4
		)

		var military_modifier = (
			0.7
			+ shortage_effect * 0.3
		)

		var transport_modifier = (
			0.5
			+ shortage_effect * 0.5
		)

		resource_efficiency_by_resource[resource_name] = (
			resource_modifier
		)

		industrial_modifier_by_resource[resource_name] = (
			industrial_modifier
		)

		military_modifier_by_resource[resource_name] = (
			military_modifier
		)

		transport_modifier_by_resource[resource_name] = (
			transport_modifier
		)

		# The country-level effect is the most restrictive
		# resource effect currently present.
		total_resource_efficiency = min(
			total_resource_efficiency,
			resource_modifier
		)

		total_industrial_modifier = min(
			total_industrial_modifier,
			industrial_modifier
		)

		total_military_modifier = min(
			total_military_modifier,
			military_modifier
		)

		total_transport_modifier = min(
			total_transport_modifier,
			transport_modifier
		)

	# ========================================================
	# SAVE UPDATED STATE
	# ========================================================

	resources.set_state(
		"production",
		production
	)

	resources.set_state(
		"reserves",
		reserves
	)

	resources.set_state(
		"stockpile",
		stockpile
	)

	resources.set_state(
		"extraction_capacity",
		extraction_capacity
	)

	resources.set_state(
		"processing_capacity",
		processing_capacity
	)

	resources.set_state(
		"net_balance",
		net_balance
	)

	resources.set_state(
		"opening_stockpile",
		opening_stockpile
	)

	resources.set_state(
		"closing_stockpile",
		closing_stockpile
	)

	resources.set_state(
		"fulfilled_demand",
		fulfilled_demand
	)

	resources.set_state(
		"stock_flow_ledger",
		stock_flow_ledger
	)

	resources.set_state(
		"stock_flow_reconciliation_error",
		stock_flow_reconciliation_error
	)

	resources.set_state(
		"opening_reserves",
		opening_reserves
	)

	resources.set_state(
		"closing_reserves",
		closing_reserves
	)

	resources.set_state(
		"reserve_flow_reconciliation_error",
		reserve_flow_reconciliation_error
	)

	resources.set_state(
		"committed_stockpile",
		committed_stockpile
	)

	resources.set_state(
		"secured_commitment",
		secured_commitment
	)

	resources.set_state(
		"commitment_shortfall",
		commitment_shortfall
	)

	resources.set_state(
		"available_stockpile",
		available_stockpile
	)

	resources.set_state(
		"available_supply",
		available_supply_by_resource
	)

	resources.set_state(
		"closing_committed_stockpile",
		closing_committed_stockpile
	)

	resources.set_state(
		"closing_available_stockpile",
		closing_available_stockpile
	)

	resources.set_state(
		"closing_commitment_shortfall",
		closing_commitment_shortfall
	)

	resources.set_state(
		"inventory_buffer_ledger",
		inventory_buffer_ledger
	)

	resources.set_state(
		"shortages",
		shortages
	)

	resources.set_state(
		"shortage_ratio",
		shortage_ratio
	)

	resources.set_state(
		"production_process_shortages",
		production_process_shortages
	)

	resources.set_state(
		"production_process_shortage_ratio",
		production_process_shortage_ratio
	)

	resources.set_state(
		"production_process_resource_availability",
		production_process_resource_availability
	)

	resources.set_state(
		"reserve_depletion",
		reserve_depletion
	)

	resources.set_state(
		"actual_production",
		actual_production
	)

	resources.set_state(
		"surplus",
		surplus
	)

	resources.set_state(
		"reserve_ratio",
		reserve_ratio
	)

	resources.set_state(
		"storage_overflow",
		storage_overflow
	)

	# ========================================================
	# SAVE PER-RESOURCE EFFECTS
	# ========================================================

	resources.set_state(
		"resource_efficiency_by_resource",
		resource_efficiency_by_resource
	)

	resources.set_state(
		"industrial_resource_modifier_by_resource",
		industrial_modifier_by_resource
	)

	resources.set_state(
		"military_resource_modifier_by_resource",
		military_modifier_by_resource
	)

	resources.set_state(
		"transport_resource_modifier_by_resource",
		transport_modifier_by_resource
	)

	# ========================================================
	# SAVE AGGREGATE EFFECTS
	# ========================================================

	resources.set_state(
		"resource_efficiency",
		clamp(
			total_resource_efficiency,
			0.0,
			1.0
		)
	)

	resources.set_state(
		"industrial_resource_modifier",
		clamp(
			total_industrial_modifier,
			0.0,
			1.0
		)
	)

	resources.set_state(
		"military_resource_modifier",
		clamp(
			total_military_modifier,
			0.0,
			1.0
		)
	)

	resources.set_state(
		"transport_resource_modifier",
		clamp(
			total_transport_modifier,
			0.0,
			1.0
		)
	)


func _collect_resource_names(
	resource_names: Dictionary,
	resource_data: Dictionary
) -> void:

	for resource_name in resource_data.keys():

		resource_names[resource_name] = true

		if catalog != null and not catalog.has_resource(str(resource_name)):
			push_warning(
				"ResourceSystem: Resource id is not defined in canonical resource catalog: "
				+ str(resource_name)
			)
