class_name PlayerActionPanel
extends PanelContainer

## Step 20.6 — Player Decision / Action Interface.
##
## This panel reads live DecisionOption objects generated by the authoritative
## DecisionSystem and submits the selected option only through
## SimulationEngine.issue_player_action().
##
## The UI does not create a second decision evaluator, action object, queue,
## validation layer, or simulation formula.

signal player_action_submitted(
	option_id: String,
	success: bool,
	message: String
)

var simulation: SimulationEngine = null
var observer: GameplayObserver = null
var player_country_id: String = "india"

var title_label: Label
var instruction_label: Label
var status_label: Label
var option_list: VBoxContainer
var refresh_button: Button


func initialize(
	live_simulation: SimulationEngine,
	live_observer: GameplayObserver,
	country_id: String = "india"
) -> void:
	simulation = live_simulation
	observer = live_observer

	if not country_id.strip_edges().is_empty():
		player_country_id = country_id.strip_edges().to_lower()

	_refresh()


func set_player_country_id(country_id: String) -> void:
	if country_id.strip_edges().is_empty():
		return

	player_country_id = country_id.strip_edges().to_lower()
	_refresh()


func refresh() -> void:
	_refresh()


func _ready() -> void:
	_build_ui()
	_refresh()


func _build_ui() -> void:
	var scroll := ScrollContainer.new()
	scroll.name = "ActionScroll"
	scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
	scroll.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	scroll.size_flags_vertical = Control.SIZE_EXPAND_FILL
	add_child(scroll)

	var margin := MarginContainer.new()
	margin.add_theme_constant_override("margin_left", 16)
	margin.add_theme_constant_override("margin_top", 14)
	margin.add_theme_constant_override("margin_right", 16)
	margin.add_theme_constant_override("margin_bottom", 14)
	scroll.add_child(margin)

	var column := VBoxContainer.new()
	column.add_theme_constant_override("separation", 7)
	margin.add_child(column)

	title_label = Label.new()
	title_label.text = "PLAYER DECISIONS"
	title_label.add_theme_font_size_override("font_size", 18)
	column.add_child(title_label)

	instruction_label = Label.new()
	instruction_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	instruction_label.text = (
        "Select a live DecisionOption. Submission uses the existing "
		+ "SimulationEngine player-action pathway."
	)
	column.add_child(instruction_label)

	refresh_button = Button.new()
	refresh_button.text = "REFRESH LIVE OPTIONS"
	refresh_button.pressed.connect(_refresh)
	column.add_child(refresh_button)

	option_list = VBoxContainer.new()
	option_list.add_theme_constant_override("separation", 8)
	column.add_child(option_list)

	status_label = Label.new()
	status_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	column.add_child(status_label)


func _clear_options() -> void:
	if option_list == null:
		return

	for child in option_list.get_children():
		child.queue_free()


func _add_option_card(option: DecisionOption) -> void:
	var panel := PanelContainer.new()
	panel.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	option_list.add_child(panel)

	var margin := MarginContainer.new()
	margin.add_theme_constant_override("margin_left", 12)
	margin.add_theme_constant_override("margin_top", 10)
	margin.add_theme_constant_override("margin_right", 12)
	margin.add_theme_constant_override("margin_bottom", 10)
	panel.add_child(margin)

	var column := VBoxContainer.new()
	column.add_theme_constant_override("separation", 5)
	margin.add_child(column)

	var name_label := Label.new()
	name_label.text = str(option.name)
	name_label.add_theme_font_size_override("font_size", 16)
	column.add_child(name_label)

	var type_label := Label.new()
	type_label.text = (
		"Type: " + str(option.action_type)
		+ " | Target: " + (
			str(option.target_id)
			if not str(option.target_id).is_empty()
			else "—"
		)
		+ " | Score: " + str(option.final_score)
	)
	type_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	column.add_child(type_label)

	var description_label := Label.new()
	description_label.text = str(option.description)
	description_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	column.add_child(description_label)

	if not option.is_available():
		var blocked_label := Label.new()
		blocked_label.text = "BLOCKED: " + str(option.blocked_reason)
		blocked_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
		column.add_child(blocked_label)
		return

	var submit_button := Button.new()
	submit_button.text = "SUBMIT ACTION"
	submit_button.pressed.connect(
		_submit_option.bind(option)
	)
	column.add_child(submit_button)


func _submit_option(option: DecisionOption) -> void:
	if option == null:
		status_label.text = "Cannot submit: decision option is null."
		return

	if simulation == null:
		status_label.text = "Cannot submit: SimulationEngine is unavailable."
		return

	if not option.is_available():
		status_label.text = (
			"Cannot submit '" + str(option.name)
			+ "': " + str(option.blocked_reason)
		)
		return

	var world := simulation.get_world()
	if world == null:
		status_label.text = "Cannot submit: WorldState is unavailable."
		return

	var result: Dictionary = simulation.issue_player_action(
		player_country_id,
		option,
		world.get_date_string()
	)

	var success: bool = bool(result.get("success", false))
	var message: String

	if success:
		var action: SimAction = result.get("action", null) as SimAction
		message = (
            "Submitted: "
			+ str(option.name)
			+ " → "
			+ str(option.target_id)
			+ " | state: "
			+ (
				str(action.state)
				if action != null
				else "queued"
			)
		)
	else:
		message = (
            "Rejected: "
			+ str(option.name)
			+ " | "
			+ str(
				result.get(
					"failure_reason",
                    "ActionManager rejected the action."
				)
			)
		)

	status_label.text = message
	player_action_submitted.emit(
		str(option.id),
		success,
		message
	)

	_refresh()


func _refresh() -> void:
	if title_label == null:
		return

	_clear_options()

	if observer == null or not observer.is_ready():
		title_label.text = "PLAYER DECISIONS — unavailable"
		status_label.text = "Authoritative observation is not ready."
		return

	var country = observer.get_country(player_country_id)
	if country == null:
		title_label.text = "PLAYER DECISIONS — country unavailable"
		status_label.text = ""
		return

	title_label.text = "PLAYER DECISIONS — " + str(country.name)

	var options: Array = observer.get_decision_options(
		player_country_id
	)

	if options.is_empty():
		status_label.text = (
            "No live decision options are currently exposed. "
			+ "Options are refreshed by the real DECISIONS phase."
		)
		return

	var typed_options: Array[DecisionOption] = []

	for raw_option in options:
		if raw_option == null:
			continue

		if not raw_option is DecisionOption:
			continue

		typed_options.append(raw_option as DecisionOption)

	for option in typed_options:
		_add_option_card(option)

	status_label.text = (
        "Live options available: "
		+ str(typed_options.size())
		+ ". Submission is validated by the authoritative player-action path."
	)
